### ISSUE TITLE
remote-m3 live lane down: every render fails with bare `com.example.designcatalogremotem3.CatalogPreviewsKt` (preview class not loadable in the bundle daemon)

### ISSUE THREAD

**Issue by yschimke** [yschimke/compose-ai-tools#2707]
## Observed (preview.coo.ee, 0.17.15, ~10 min after roll)

`/status.json` → `runningServers[]` for `remote-m3` (android):

```json
{ "renders": 8, "ok": 0, "failed": 8, "timedOut": 0,
  "lastFailureReason": "render failed: com.example.designcatalogremotem3.CatalogPreviewsKt" }
```

Every render of the remote-m3 catalog's live lane fails fast (no timeouts — the renderFailed fail-fast from #2687 is working) and the composite silently serves baked fallback, so browsing looks fine while the live lane is fully down. Every other catalog is healthy on the same box (confetti-mobile first render 4.1 s, confetti-wear 5.8 s, meshcore-mobile 7.6 s; steady-state p50 ~0.5 s).

## Diagnosis

A failure message that is *just a class FQN* is the signature of a `ClassNotFoundException` / `NoClassDefFoundError` surfacing through `renderFailed` — the daemon cannot load the catalog's own preview class `com.example.designcatalogremotem3.CatalogPreviewsKt`. Since this is the Remote Compose catalog, the likely candidates:

1. The remote-m3 `liveBundle`'s resolved classpath is missing the alpha `androidx.compose.remote.*` (creation/player) coordinates, so loading `CatalogPreviewsKt` fails resolving a referenced RC type (`NoClassDefFoundError` whose message is the initiating class). The daemon's connector gating (`isRemoteComposeAvailable`) only guards the *extension* registration — the preview class itself still links against RC types at class-load time.
2. Or `classes/app.jar` in the packed bundle doesn't carry the class at all (pack-time regression in the `design-artifacts` export for this catalog).

Either way it's a **bundle packing / classpath issue for this one catalog**, not a render-pipeline problem. The `renders: 8, failed: 8` pattern is serve's warm loop retrying — cheap now, but the retries will continue indefinitely.

## Repro

```bash
curl -s https://preview.coo.ee/status.json | jq '.runningServers[] | select(.id=="remote-m3").renderStats'
# or locally: fetch the remote-m3 bundle from design-artifacts/remote-m3 and
# `compose-preview bundle render <bundle> --knob x=y --verbose` — expect
# "render failed: com.example.designcatalogremotem3.CatalogPreviewsKt" per preview.
```

Container logs will carry the full stack (`compose-ai-daemon: [render] phase=…failed`), which pins down candidate 1 vs 2.

## Polish (small, separable)

The reason string is a bare FQN because `ServeRenderHost` carries only the daemon's `error.message`, and a CNFE/NCDFE's message *is* the class name. Prefixing the exception class daemon-side (e.g. `NoClassDefFoundError: com.example…`) — the daemon already knows it when it builds `RenderFailedParams` — would make `lastFailureReason` self-explanatory. (`RenderError.stackTrace` exists on the wire already; only the message needs enriching.)
