### ISSUE TITLE
Compose Preview: fix the resources/previews that render no PNG, then flip missing-renders back to fail

### ISSUE THREAD

**Issue by yschimke** [yschimke/compose-ai-tools#2159]
## Context

The **Compose Preview** workflow was chronically red on `main` for days: the render pipelines run `compose-preview show` / `show-resources` under the default `missing-renders: fail` policy, and some resources/previews reliably produce **no output PNG** (e.g. the launcher-icon adaptive-icon variants — the rasterizer jitter tracked in #2133), so the job hard-failed at RC-aggregation (`rc=2`).

## What's already been done (mitigation, not the fix)

- **#2141** — `apply` action's compose-comment step no longer crashes on an empty `_previews.json` (was masking the `rc=2` on no-op PRs).
- **#2151** — set `missing-renders: warn` on this repo's caller of the `apply` action (`.github/workflows/compose-preview.yml`), so stubborn renders log instead of gating CI. **Caller-scoped**; the action default stays `fail` for external consumers.
- **#2156** — fixed `ShowResourcesCommand` to actually honor `--missing-renders` (it previously `exitProcess(2)` unconditionally, so `warn` did nothing for the resources pipeline). It now prints a **per-variant offender list** and only hard-fails under `fail`.

Together these take the check green, **but the underlying missing renders are still real** — CI is just no longer gating on them.

## What remains (this issue)

1. **Enumerate the culprits.** They're now self-diagnosing in the Compose Preview run logs (no artifact download needed) — look for, in the resources pipeline:
   ```
   missing-renders policy=warn — Resource render completed but produced no PNG for N of M resource preview(s):
     - <id> (<module>) — no PNG for: <renderOutput variant>, …
   ```
   and the analogous `Render task completed but produced no PNG …` block from the compose pipeline.
2. **Fix the renders** so those variants produce PNGs (or, if a variant is legitimately non-PNG, exclude it the way `NON_PNG_PREVIEW_KINDS` handles XR subspace). Likely overlaps with the adaptive-icon rasterizer jitter in #2133.
3. **Flip back to `fail`.** Once the missing renders are gone, remove the `missing-renders: warn` override in `.github/workflows/compose-preview.yml` (there's a comment there pointing here) so the check regains its hard-fail guarantee.

## Exit criteria

- Compose Preview is green on `main` under the default `missing-renders: fail` policy (override removed), with no null-PNG resources/previews in the run logs.

Related: #2133, #2141, #2151, #2156.

**Comment by yschimke** [comment]
### Second failure surface: `rc=1` (not just the missing-render `rc=2`)

Heads-up for the "restore green under `fail`" goal — there's more than the missing renders.

Once #2156 (which makes `show-resources` honor `--missing-renders`) was in the base and `warn` was active, a #2151 run's `Apply compose-preview` **still failed, but with `rc=1`** (`WORST_RC=1`), not the missing-render `rc=2`. The resource-diff comment on that run had gone to *"No resource changes"* (clean), i.e. the resources pipeline was no longer the failure — so a **different, previously-masked pipeline failure** surfaced. The RC-aggregation loop had always reported resources' `rc=2` first, hiding anything after it in the `compose → resources → a11y → notifications` order.

So the picture is:
- **rc=2** — resources/previews that render no PNG (the missing-render issue this ticket is about). Now `warn`-tolerated in CI.
- **rc=1** — a separate pipeline (one of `compose` / `a11y` / `notifications`) exiting non-zero for a *different* reason. Pipeline TBD — it's in the run's mid-log under the matching `::group::<name> pipeline` section (I couldn't page to it via the API's tail-only log access; it's visible in the GitHub Actions UI).

**Implication:** #2151 + #2156 stop the check *gating* merges (it's non-required), but the check won't be truly green — and thus can't be flipped back to `fail` per the exit criteria above — until this `rc=1` pipeline is also identified and fixed. Whoever picks this up: grab the `rc=1` pipeline name from the next Compose Preview run's mid-log and fold it in here (or split a sibling issue if it's unrelated to rendering, e.g. an a11y/notifications-specific error). It's also worth a single re-run to rule out a transient (push/step flake).

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by yschimke** [comment]
### The hidden pipeline failure is identified and fixed (#2183)

The `rc=2` that kept the check red even after `missing-renders: warn` was **not** a missing-render — it was `compose-preview show` exiting 2 via the hard "Render failed" path (`buildOk=false`), on every run since the #2104 dependency bump:

- xr-compose **alpha15**'s `Meter.DP_PER_METER` now probes `XrExtensionsHolderAccessor` on the first `Subspace` layout.
- The accessor `Class.forName`s the on-device `SpatialCoreXrExtensionsHolderProvider` first, and scenecore **alpha16** ships `scenecore-spatial-core` as a *runtime* dep — so the class is present on the render classpath, but its `<clinit>` references the device-only `com.android.extensions.xr.XrExtensions`.
- The accessor only catches `ClassNotFoundException`, not the resulting `NoClassDefFoundError`, so all 12 `:samples:xr-spatial:composePreviewRenderXr` renders failed → `composePreviewRenderAll` failed → `show` (and the a11y run) exited non-zero → `rc=2`. This is also why the `compose-preview/main` and `compose-preview/a11y/main` baselines were frozen at Jun 29 while resources/notifications kept updating.

#2183 filters `scenecore-spatial-{core,rendering}` out of the `composePreviewRenderXr` classpath (per path segment, artifact shapes only) so the probe falls back to `scenecore-testing`'s `FakeXrExtensionsHolderProvider`. The Compose Preview check is green on that PR — first green run since Jun 29.

**Still open for this issue's exit criteria** (flip back to `fail`): the genuine missing renders, currently `samples:cmp/colorcatalog__Brand` (no PNG) per the PR-run diff comment, plus the #2133 launcher-icon jitter.

---
_Generated by [Claude Code](https://claude.ai/code)_
